# this is used for testing jx inside a cluster in development
FROM gcr.io/jenkinsxio/builder-machine-learning:0.1.662

COPY build/helm /home/jenkins/.jx/bin/helm3
COPY build/helm /usr/bin/helm3
COPY build/linux/jx /usr/bin/jx